# Generated by Django 2.0.3 on 2018-07-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20180707_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='contact',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
