# Generated by Django 2.0.3 on 2018-07-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dp',
            field=models.ImageField(blank=True, upload_to='dp_pics'),
        ),
    ]
